.TH ROPIPE 1 "23 December 2022"
.SH NAME
plagiacode - Levenshtein Distance based code plagiarism evaluating tool
.SH SYNOPSIS
plagiacode [ -v | -h | -i -ve -r]
.SH DESCRIPTION
Plagiacode is a fast hasmap-based c++ utility to evaluate possible code plagiarism on a set of files/directories with Levenshtein Distance.
.SS Options
.TP
-v
Display version info
.TP
-h
Display help
.TP
-i
Perform whitespace-sensistive search
.TP
-ve
Enable verbose output
.TP
-r
Do not perform recursive search
.SH BUGS
Send bug reports to https://github.com/MatMasIt/plagiacode